oTree/pgg_chat/urls.py
# urls.py
from django.conf.urls import url
from otree.default_urls import urlpatterns

urlpatterns.append(url(r'^send_message$', 'pgg_chat.custom_views.send_message'))
urlpatterns.append(url(r'^get_messages$', 'pgg_chat.custom_views.get_messages'))

oTree/vickrey_auction/models.py
# -*- coding: utf-8 -*-
# <standard imports>
from __future__ import division
from otree.db import models
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer, BaseLink

from otree import widgets
from otree.common import Currency as c, currency_range
import random
# </standard imports>


doc = """
In this Vickrey auction, 3 players bid for an object with private values. Each
player can only submit one bid.

"""


source_code = "https://github.com/oTree-org/oTree/tree/master/vickrey_auction"


bibliography = (
    (
        'Vickrey, William. "Counterspeculation, auctions, and competitive '
        'sealed tenders." The Journal of finance 16.1 (1961): 8-37'
    ),
)


links = {
    "Wikipedia": {
        "Vickrey Auction": "http://en.wikipedia.org/wiki/Vickrey_auction",
        "Generalized Second-Price Auction":
            "http://en.wikipedia.org/wiki/Generalized_second-price_auction",
        "Auction": "http://en.wikipedia.org/wiki/Auction",
    }
}


keywords = (
    "Auction", "Second-Price Auction",
    "Vickrey Auction", "Sealed-Bid Auction"
)


class Constants(BaseConstants):
    name_in_url = 'vickrey_auction'
    players_per_group = 3
    num_rounds = 1

    fixed_payoff = c(100)
    min_allowable_bid = c(0)
    max_allowable_bid = c(100)

    training_question_1_my_payoff_limit = c(100) * players_per_group
    training_question_1_my_payoff_correct = c(105)


class Subsession(BaseSubsession):
    def before_session_starts(self):
        for p in self.get_players():
            p.private_value = random.randint(
            Constants.min_allowable_bid, Constants.max_allowable_bid
        )


class Group(BaseGroup):

    def highest_bid(self):
        return max([p.bid_amount for p in self.get_players()])

    def second_highest_bid(self):
        values = sorted(
            (p.bid_amount for p in self.get_players()), reverse=True
        )
        return values[1]

    def set_winner(self):
        players_with_highest_bid = [
            p for p in self.get_players()
            if p.bid_amount == self.highest_bid()
        ]
        # if tie, winner is chosen at random
        winner = random.choice(players_with_highest_bid)
        winner.is_winner = True

    def set_payoffs(self):
        second_highest_bid = self.second_highest_bid()
        for p in self.get_players():
            p.payoff = Constants.fixed_payoff
            if p.is_winner:
                p.payoff += (
                    p.private_value - second_highest_bid
                )
                if p.payoff < 0:
                    p.payoff = 0

class Link(BaseLink):
    pass

class Player(BasePlayer):

    private_value = models.CurrencyField(
        null=True,
        doc="How much the player values the item, generated randomly"
    )

    bid_amount = models.CurrencyField(
        null=True,
        min=Constants.min_allowable_bid, max=Constants.max_allowable_bid,
        doc="Amount bidded by the player"
    )

    is_winner = models.BooleanField(
        initial=False,
        doc="""Indicates whether the player is the winner"""
    )

    training_question_1_my_payoff = models.CurrencyField()

    def is_training_question_1_my_payoff_correct(self):
        return (self.training_question_1_my_payoff==
                Constants.training_question_1_my_payoff_correct)

oTree/vickrey_auction/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from . import models
from ._builtin import Page, WaitPage
from otree.common import Currency as c, currency_range
from .models import Constants


def vars_for_all_templates(self):

    return {'total_q': 1
            # 'total_rounds': Constants.num_rounds,
            # 'round_number': self.subsession.round_number
            }


class Introduction(Page):
    pass

class Question(Page):

    def is_displayed(self):
        return self.subsession.round_number == 1

    form_model = models.Player
    form_fields = ['training_question_1_my_payoff']

    def vars_for_template(self):
        return {'num_q': 1}


class Feedback1(Page):

    template_name = 'vickrey_auction/Feedback.html'

    def vars_for_template(self):
        return {
            'num_q': 1
        }


class Bid(Page):

    form_model = models.Player
    form_fields = ['bid_amount']


class ResultsWaitPage(WaitPage):

    def after_all_players_arrive(self):
        self.group.set_winner()
        self.group.set_payoffs()


class Results(Page):
    pass


page_sequence = [Introduction,
            Question,
            Feedback1,
            Bid,
            ResultsWaitPage,
            Results]

oTree/vickrey_auction/templates/vickrey_auction/Bid.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Bid
{% endblock %}

{% block styles %}
<link href="{% static "vickrey_auction/jquery-ui/jquery-ui.min.css" %}" rel="stylesheet">
<style type="text/css">
    .bid-slider {
        margin: 1.5em auto;
        width: 70%;
    }

    .bid {
        text-align: center;
    }

    .payoff {
        margin: 1.5em 0;
    }
</style>
{% endblock %}

{% block scripts %}
<script src="{% static "vickrey_auction/jquery-ui/jquery-ui.min.js" %}"></script>
<script>
jQuery(document).ready(function ($) {
    var PRIVATE_VALUE = {{ player.private_value.to_number|escapejs }};

    var input = $('#id_bid_amount');

    $('.bid-slider').slider({
        min: 0,
        max: 100,
        slide: function (event, ui) {
            input.val(ui.value);
            updateBidValue();
        },
    });

    function updateBidValue() {
        $('.bid-value').text(input.val());
        $('.payoff-value').text(calculatePayoff());
    }

    function calculatePayoff() {
        var value = parseInt(input.val());
        var payoff = 100 + PRIVATE_VALUE;
        return payoff;
    }

    updateBidValue();
});
</script>
{% endblock %}

{% block content %}

    <p>
        Your value to the object is <strong>{{ player.private_value }}</strong>.
    </p>

    <div class="form-group required">
        <label class="control-label" for="id_bid_amount">Please submit a bid for the object (from 0 to 100):</label>
        <div class="controls">
            <input type="hidden" name="bid_amount" id="id_bid_amount" value="0">
            <div class="bid-slider"></div>
            <div class="bid">Your bid: <strong><span class="bid-value"></span> points</strong></div>
            <div class="payoff">If you win the auction, you would have a payoff of <strong><span class="payoff-value"></span> points - Second highest bid</strong>.</div>
        </div>
    </div>

    {% next_button %}

    {% include Constants.instructions_template %}

{% endblock %}

oTree/vickrey_auction/templates/vickrey_auction/Feedback.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Solution to Understanding Question {{ num_q }} of {{ total_q }}
{% endblock %}

{% block content %}



    {% if player.is_training_question_1_my_payoff_correct %}
        <p class="text-success">Your answer {{player.training_question_1_my_payoff}} was correct.</p>
    {% else %}
        <p class="text-danger">Your answer {{player.training_question_1_my_payoff}} was incorrect</p>
    {% endif %}


    <p>
        Suppose that your value to the object was 65 points and you bid 60.
        The other 2 participants bid 55 and 45 respectively.
        What would be your payoff?
    </p>
    <p>
        <strong>Solution: {{Constants.training_question_1_my_payoff_correct}}.</strong>
    </p>
    <p>
        <strong>Explanation:</strong> You bid 60 which was the highest among
        all bids (60, 55, 45), thus you won the object. You paid the second
        highest bid, which was <strong>55</strong>. Since the object valued
        <strong>65</strong> to you, your payoff was
        <strong>100+65-55={{Constants.training_question_1_my_payoff_correct}}</strong>.
    </p>

    {% next_button %}

    {% include 'vickrey_auction/Instructions.html' %}

{% endblock %}

oTree/vickrey_auction/templates/vickrey_auction/Instructions.html
<style type="text/css">
    ul {
        list-style-type:circle;
        padding-left:20px;
    }
    h3.panel-sub-heading {
        padding-bottom:10px;
        padding-left:4px;
    }

    td, th{
        text-align: center;
    }

    .rotate90 {
        -webkit-transform: rotate(-90deg);
        -moz-transform: rotate(-90deg);
        -ms-transform: rotate(-90deg);
        -o-transform: rotate(-90deg);
        transform: rotate(-90deg);
        position: absolute;
        top: 60%;
    }

    .instructions {
        position: relative;
        text-shadow: 0 1px 0 #fff;
        line-height: 1.5;
        margin: 60px auto;
        background-color: #f5f5dc;
        background-image: linear-gradient(to bottom, #f5f5dc 0px, #fbfbeb 100%);
        padding-top: 5px;
        padding-bottom: 15px;
        margin-top: 20px;
        -moz-border-radius: 4px;
        border-radius: 4px;
    }

    .instructions:before, .instructions:after {
        z-index: -1;
        position: absolute;
        content: "";
        bottom: 15px;
        left: 10px;
        width: 50%;
        top: 80%;
        max-width:300px;
        background: rgba(0, 0, 0, 0.7);
        box-shadow: 0 15px 10px rgba(0, 0, 0, 0.7);
        transform: rotate(-3deg);
    }

    .instructions:after {
        transform: rotate(3deg);
        right: 10px;
        left: auto;
    }
</style>

<div class="instructions well well-lg" style="">

    <h3 class="panel-sub-heading">
        Instructions
    </h3>

    <p>
        You have been randomly and anonymously matched with another 2
        participants in an auction. Each of you is given 100 points to start.
    </p>
    <p>
        Before bidding, you will learn the value of the object to you. The
        value of the object differs from participant to participant and is
        randomly and independently drawn from 0 to 100 for each participant.
    </p>
    <p>
        At auction, you will privately submit one bid for the object. A bid
        can be anything from 0 to 100 points. The participant with the highest
        bid wins the object and pays the second highest bid. A random device
        will select the winner in the event of a tie bid and the winner will
        pay the highest bid other than her or his own bid.
    </p>
    <p>
        The payoff of the winner is calculated as (in points)<br/>
        <strong>
            Winner’s payoff = 100 + Private value of the object to the winner - Second highest bid
        </strong><br/>
        The payoffs for others are the initial 100 points.
    </p>
    <p>
        For your convenience, these instructions will remain available to you on all subsequent screens of this study.
    </p>

</div>

oTree/vickrey_auction/templates/vickrey_auction/Introduction.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Introduction{% endblock %}{% block content %}    {% include 'vickrey_auction/Instructions.html' %}    <p>       On the next page, you will have to answer one question to make sure you understand the instructions correctly.    </p>    {% next_button %}{% endblock %}

oTree/vickrey_auction/templates/vickrey_auction/Question.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Understanding Question {{ num_q }} of {{ total_q }}
{% endblock %}

{% block content %}

    {% if num_q == 1 %}
        <p>
            You were given 100 points to start. Suppose that your value to the
            object was 65 points and you bid 60. The other 2 participants bid
            60 and 45 respectively. A coin was flipped and you were selected
            to be the winner. What would be your payoff?
        </p>
        <p>
            {% formfield player.training_question_1_my_payoff with label='My payoff would be:' %}
        </p>
    {% endif %}

    {% next_button %}

    {% include 'vickrey_auction/Instructions.html' %}

{% endblock %}

oTree/vickrey_auction/templates/vickrey_auction/Results.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Results
{% endblock %}

{% block content %}



    <p>
        {% if player.is_winner %}
            You won the auction!
        {% else %}
            You did not win the auction!
        {% endif %}
    </p>

    <table class="table">
        <tr>
            <th>Your value</th>
            <th>Your bid</th>
            <th>Winning bid</th>
            <th>Second-Highest Bid</th>
            <th>You Paid</th>
            <th>Your payoff</th>
        </tr>

        <tr>
            <td>{{ player.private_value }}</td>
            <td>{{ player.bid_amount }}</td>
            <td>{{ group.highest_bid }}</td>
            <td>{{ group.second_highest_bid }}</td>
            <td>
                {% if player.is_winner %}
                    {{ group.second_highest_bid }}
                {% else %}
                    0
                {% endif %}
            </td>
            <td>{{ player.payoff|floatformat:"-2" }}</td>
        </tr>

    </table>

    {% next_button %}

    {% include 'vickrey_auction/Instructions.html' %}

{% endblock %}